# Generated by Django 3.1.7 on 2021-04-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.IntegerField(blank=True, null=True)),
                ('wind_dir', models.CharField(blank=True, max_length=20, null=True)),
                ('weather_con', models.CharField(blank=True, max_length=20, null=True)),
                ('temper', models.CharField(blank=True, max_length=20, null=True)),
                ('hum', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': '气象情况',
            },
        ),
        migrations.CreateModel(
            name='Fight_com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('person', models.CharField(blank=True, max_length=20, null=True)),
                ('see_com', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('fire_zs', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_change', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '作战指挥情况',
            },
        ),
        migrations.CreateModel(
            name='First_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('develop', models.CharField(blank=True, max_length=20, null=True)),
                ('person', models.IntegerField(blank=True, null=True)),
                ('fire_recon', models.CharField(blank=True, max_length=20, null=True)),
                ('danger', models.BooleanField(blank=True, default=False, null=True)),
                ('fight_task', models.CharField(blank=True, max_length=20, null=True)),
                ('build_map', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': '第一支消防队到场情况',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[(0, '男'), (1, '女')], max_length=15, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person_hurt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('死亡人数', models.IntegerField(blank=True, null=True)),
                ('重伤人数', models.IntegerField(blank=True, null=True)),
                ('轻伤人数', models.IntegerField(blank=True, null=True)),
                ('男性死亡人数', models.IntegerField(blank=True, null=True)),
                ('女性死亡人数', models.IntegerField(blank=True, null=True)),
                ('本地死亡人数', models.IntegerField(blank=True, null=True)),
                ('外地死亡人数', models.IntegerField(blank=True, null=True)),
                ('dead_people1', models.IntegerField(blank=True, null=True)),
                ('dead_people2', models.IntegerField(blank=True, null=True)),
                ('dead_people3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '人员伤亡情况',
            },
        ),
        migrations.CreateModel(
            name='Save_eq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('水罐车', models.BooleanField(blank=True, default=False, null=True)),
                ('泡沫水罐车', models.BooleanField(blank=True, default=False, null=True)),
                ('高倍水罐车', models.BooleanField(blank=True, default=False, null=True)),
                ('二氧化碳消防车', models.BooleanField(blank=True, default=False, null=True)),
                ('干粉消防车', models.BooleanField(blank=True, default=False, null=True)),
                ('泡沫干粉联用消防车', models.BooleanField(blank=True, default=False, null=True)),
                ('登高平台消防车', models.BooleanField(blank=True, default=False, null=True)),
                ('云梯消防车', models.BooleanField(blank=True, default=False, null=True)),
                ('通讯消防车', models.BooleanField(blank=True, default=False, null=True)),
                ('save_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com')),
            ],
            options={
                'db_table': '救援装备使用情况',
            },
        ),
        migrations.CreateModel(
            name='Person_eq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('头盔', models.CharField(blank=True, max_length=20, null=True)),
                ('防护服', models.CharField(blank=True, max_length=20, null=True)),
                ('呼吸器', models.CharField(blank=True, max_length=20, null=True)),
                ('手防护', models.CharField(blank=True, max_length=20, null=True)),
                ('足防护', models.CharField(blank=True, max_length=20, null=True)),
                ('per_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com')),
            ],
            options={
                'db_table': '个人防护装备使用情况',
            },
        ),
        migrations.CreateModel(
            name='Firesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(max_length=50)),
                ('detal_place', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('fire_type', models.CharField(max_length=10)),
                ('fire_level', models.CharField(max_length=10)),
                ('last_time', models.CharField(blank=True, max_length=10, null=True)),
                ('major_th', models.CharField(blank=True, max_length=20, null=True)),
                ('fire_build', models.BooleanField(default=True)),
                ('water', models.BooleanField(default=True)),
                ('air', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire.air')),
            ],
            options={
                'db_table': '火灾基本情况',
            },
        ),
        migrations.CreateModel(
            name='Fire_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('消防人员', models.BooleanField(blank=True, default=False, null=True)),
                ('群众', models.BooleanField(blank=True, default=False, null=True)),
                ('部队', models.BooleanField(blank=True, default=False, null=True)),
                ('专家', models.BooleanField(blank=True, default=False, null=True)),
                ('政府', models.BooleanField(blank=True, default=False, null=True)),
                ('交警', models.BooleanField(blank=True, default=False, null=True)),
                ('公安', models.BooleanField(blank=True, default=False, null=True)),
                ('医疗', models.BooleanField(blank=True, default=False, null=True)),
                ('安监', models.BooleanField(blank=True, default=False, null=True)),
                ('save_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com')),
            ],
            options={
                'db_table': '火灾救援人员情况',
            },
        ),
        migrations.AddField(
            model_name='fight_com',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire.first_team'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('fire_economic', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_cause', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_res', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_exper', models.CharField(blank=True, max_length=100, null=True)),
                ('fire_com', models.CharField(blank=True, max_length=100, null=True)),
                ('dis_mea', models.CharField(blank=True, max_length=100, null=True)),
                ('dead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire.person_hurt')),
            ],
            options={
                'db_table': '经验总结分析',
            },
        ),
        migrations.CreateModel(
            name='Build_char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_bulid', models.BooleanField(default=False, null=True)),
                ('old_build', models.BooleanField(default=False, null=True)),
                ('wuzi_ck', models.BooleanField(default=False, null=True)),
                ('product_cq', models.BooleanField(default=False, null=True)),
                ('chugq', models.BooleanField(default=False, null=True)),
                ('hall_build', models.BooleanField(default=False, null=True)),
                ('bfire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.firesi')),
            ],
            options={
                'db_table': '建筑结构特点',
            },
        ),
    ]
