# Generated by Django 3.1.7 on 2021-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_auto_20210402_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build_char',
            name='chugq',
            field=models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build_char',
            name='com_bulid',
            field=models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build_char',
            name='hall_build',
            field=models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build_char',
            name='old_build',
            field=models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build_char',
            name='product_cq',
            field=models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build_char',
            name='wuzi_ck',
            field=models.CharField(choices=[('True', '是'), ('False', '否'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='专家',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='交警',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='公安',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='医疗',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='安监',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='政府',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='消防人员',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='群众',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_save',
            name='部队',
            field=models.CharField(blank=True, choices=[('True', '到场'), ('False', '未到场'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firesi',
            name='fire_build',
            field=models.CharField(choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firesi',
            name='water',
            field=models.CharField(choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='first_team',
            name='build_map',
            field=models.CharField(blank=True, choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='first_team',
            name='danger',
            field=models.CharField(blank=True, choices=[('True', '有'), ('False', '没有'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='二氧化碳消防车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='云梯消防车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='干粉消防车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='水罐车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='泡沫干粉联用消防车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='泡沫水罐车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='登高平台消防车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='通讯消防车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='save_eq',
            name='高倍水罐车',
            field=models.CharField(blank=True, choices=[('True', '使用'), ('False', '未使用'), ('Null', '未知')], default=False, max_length=20, null=True),
        ),
    ]
