# Generated by Django 3.1.7 on 2021-04-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0004_auto_20210402_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_eq',
            name='save_eq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.fight_com'),
        ),
    ]
