# Generated by Django 3.1.7 on 2021-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0005_auto_20210402_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firesi',
            name='fire_level',
            field=models.CharField(blank=True, choices=[('A', '一般火灾'), ('B', '较大火灾'), ('C', '重大火灾'), ('D', '特别重大火灾'), ('Null', '未知')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='firesi',
            name='fire_type',
            field=models.CharField(blank=True, choices=[('A', 'A类'), ('B', 'B类'), ('C', 'C类'), ('D', 'D类'), ('E', 'E类'), ('F', 'F类'), ('Null', '未知')], max_length=10, null=True),
        ),
    ]
