# Generated by Django 3.1.7 on 2021-04-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0007_pictest'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='goods_pic',
            field=models.ImageField(default='', upload_to='fire'),
        ),
    ]
