# Generated by Django 3.1.7 on 2021-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0008_person_goods_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firesi',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='air',
            table=None,
        ),
        migrations.AlterModelTable(
            name='build_char',
            table=None,
        ),
        migrations.AlterModelTable(
            name='experience',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fight_com',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fire_save',
            table=None,
        ),
        migrations.AlterModelTable(
            name='firesi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='first_team',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person_eq',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person_hurt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='save_eq',
            table=None,
        ),
    ]
