# Generated by Django 3.1.7 on 2021-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0009_auto_20210606_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight_com',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
