# Generated by Django 3.1.7 on 2021-06-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0010_auto_20210607_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cgy', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '火灾类别表',
                'verbose_name_plural': '火灾类别表',
            },
        ),
        migrations.CreateModel(
            name='FireInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LevelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lev', models.CharField(db_column='火灾等级', max_length=30)),
            ],
            options={
                'verbose_name': '火灾等级表',
                'verbose_name_plural': '火灾等级表',
            },
        ),
        migrations.CreateModel(
            name='SpeedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrappedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trapped', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('Pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.categoryinfo')),
            ],
            options={
                'verbose_name': '火灾地点表',
                'verbose_name_plural': '火灾地点表',
            },
        ),
        migrations.CreateModel(
            name='InjuredInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injured', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FireRuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
                ('call', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=20)),
                ('fire', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('trapped', models.CharField(max_length=20)),
                ('injured', models.CharField(max_length=20)),
                ('death', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
            options={
                'verbose_name': '火灾属性表',
                'verbose_name_plural': '火灾属性表',
            },
        ),
        migrations.CreateModel(
            name='DecisionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.TextField()),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
                ('Pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.categoryinfo')),
            ],
            options={
                'verbose_name': '火灾决策方案表',
                'verbose_name_plural': '火灾决策方案表',
            },
        ),
        migrations.CreateModel(
            name='DeathInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('Alev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.levelinfo')),
            ],
        ),
    ]
